# TensorFlow's eager execution is an imperative programming environment that evaluates operations immediately, without building graphs: operations return concrete values instead of constructing a computaional graph to run it later.

Eager execution is a flexible machine learning platform for research and experimentation,providing:
    
    An intuitive interface - Structure your code naturally and use Python data structures. Quickly iterate on small models and small data.
    Easier debugging - Call ops directly to inspect running models and test changes. Use standard Python debugging tools for immediate error reporting.
    Natural control flow - Use Python control flow instead of graph control flow, simplifying the specification of dynamic models.
    
    Eager execution supports most Tensorflow operations and GPU acceleration.

# Setup and basic usage

In [1]:
import os

import tensorflow as tf

import cProfile

In [2]:
#In Tensorflow 2.x, eager execution is enabled by default

tf.executing_eagerly()

True

In [3]:
#Now you can run Tensorflow operations and the results will return immediately

x  = [[2.]]
m = tf.matmul(x,x)
print("hello, {}".format(m))

hello, [[4.]]


In [4]:
a = tf.constant([[1, 2],
               [3, 4]])
print(a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [5]:
#Broadcasting support
b = tf.add(a, 1)
print(b)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [6]:
#Operator overloading is supported
print(a * b)

tf.Tensor(
[[ 2  6]
 [12 20]], shape=(2, 2), dtype=int32)


In [7]:
#Use numpy values
import numpy as np

c = np.multiply(a, b)
print(c)

[[ 2  6]
 [12 20]]


In [8]:
#Obtain numpy value from a tensor:
print(a.numpy())
# => [[1 2]]
#     [3 4]

[[1 2]
 [3 4]]


# Dynamic control flow

A major benefit of eager execution is that all the functionality of the host langauge is available while your model is executing. So, for example,it is easy to write fizzbuzz:

In [9]:
def fizzbuzz(max_num):
    counter = tf.constant(0)
    max_num = tf.convert_to_tensor(max_num)
    for num in range(1, max_num.numpy()+1):
        num = tf.constant(num)
        if int(num % 3) == 0 and int(num % 5) == 0:
            print('FizzBuzz')
        elif int(num % 3) == 0:
            print('Fizz')
        elif int(num % 5) == 0:
            print('Buzz')
        else:
            print(num.numpy())
        counter += 1

In [10]:
fizzbuzz(15)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz


Computing gradients

Automatic differentiation is useful for implementing machine learning algorithms such as backpropagation for training neural networks. During eager execution,use tf.GradientTape to trace operations for computing gradients later.

You can use tf.GradientTape to train and/or compute gradients in eager. It is especially useful for complicated training loops.

Since different operations can occur during each call, all forward-pass operations get gradient,play the tape backwards and then discard. A particular tf.GradientTape can only compute one gradient; subsequent calls throw a runtime error

In [11]:
w = tf.Variable([1.0])
with tf.GradientTape() as tape:
    loss = w*w
    
grad = tape.gradient(loss, w)
print(grad) # => tf.Tensor([[2.]], shape=(1,1), dtype=float32)

tf.Tensor([2.], shape=(1,), dtype=float32)
